language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  -  EMAIL_HOST_USER=abc@example.com EMAILHOST_PASSWORD=34wdf
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  -  pip install -r requirements.txt 
  -  pip install coveralls
# command to run tests, e.g. python setup.py test
script:  
  -  python manage.py test
  -  coverage run --source="." manage.py test api application

after_success:
  -  coveralls