language: python
python:
  - "3.3"
  - "2.7"
  - "2.6"
env:
  - EMAIL_HOST_USER=abc@def.com  EMAIL_HOST_PASSWORD=ae34  SECRET_KEY= abcd
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install: 
  -  pip install -r requirements.txt  --use-mirrors
  -  pip install coveralls  --use-mirrors
# command to run tests, e.g. python setup.py test
script:  
  -  python manage.py test 
  -  coverage run --source="." manage.py test 
after_success:
  -  coveralls